[workspace]
authors = ["sara-graca <saravsgraca@gmail.com>"]
channels = ["conda-forge"]
name = "numerical-stability"
platforms = ["win-64"]
version = "0.1.0"

[tasks]

[dependencies]
python = "3.10.*"
numpy = "*"
pandas = "*"
scipy = "*"
matplotlib = "*"
pysoundfile = ">=0.13.1,<0.14"
pyarrow = ">=23.0.1,<24"
dvc = ">=3.67.1,<4"
tqdm = ">=4.67.3,<5"

[pypi-dependencies]
torch = "*"
torchaudio = "*"
transformers = "*"
textgrid = "*"
chardet = "*"
tgt = "*"
soundfile = "*"
